import { NextResponse } from "next/server";

// Pricing tiers - matches backend config
const PRICING_TIERS = [
  {
    tier: "free",
    name: "Free",
    description: "Get started with basic legal research",
    monthlyPrice: 0,
    annualPrice: 0,
    isPerSeat: false,
    minSeats: 1,
    trialDays: 0,
    limits: {
      monthlyAiQueries: 50,
      storageGb: 1,
      maxMembers: 1,
      monthlyDeepResearch: 0,
      monthlyContractDrafts: 0,
      monthlyContractAnalyses: 0,
      chatHistoryDays: 7,
      monthlyApiCalls: 0,
    },
    features: {
      basicSearch: true,
      aiChat: true,
      citations: true,
      deepResearch: false,
      contractDrafting: false,
      contractAnalysis: false,
      documentUpload: false,
      exportPdf: false,
      exportDocx: false,
      teamManagement: false,
      roleBasedAccess: false,
      sharedWorkspaces: false,
      activityLogs: false,
      ssoSaml: false,
      customIntegrations: false,
      apiAccess: false,
      dedicatedSupport: false,
    },
  },
  {
    tier: "professional",
    name: "Professional",
    description: "For individual legal professionals",
    monthlyPrice: 25,
    annualPrice: 20,
    isPerSeat: false,
    minSeats: 1,
    trialDays: 14,
    limits: {
      monthlyAiQueries: 500,
      storageGb: 10,
      maxMembers: 1,
      monthlyDeepResearch: 20,
      monthlyContractDrafts: 10,
      monthlyContractAnalyses: 20,
      chatHistoryDays: 90,
      monthlyApiCalls: 0,
    },
    features: {
      basicSearch: true,
      aiChat: true,
      citations: true,
      deepResearch: true,
      contractDrafting: true,
      contractAnalysis: true,
      documentUpload: true,
      exportPdf: true,
      exportDocx: true,
      teamManagement: false,
      roleBasedAccess: false,
      sharedWorkspaces: false,
      activityLogs: false,
      ssoSaml: false,
      customIntegrations: false,
      apiAccess: false,
      dedicatedSupport: false,
    },
  },
  {
    tier: "team",
    name: "Team",
    description: "For law firms and legal teams",
    monthlyPrice: 30,
    annualPrice: 25,
    isPerSeat: true,
    minSeats: 3,
    trialDays: 14,
    limits: {
      monthlyAiQueries: 2000,
      storageGb: 100,
      maxMembers: 50,
      monthlyDeepResearch: 100,
      monthlyContractDrafts: 50,
      monthlyContractAnalyses: 100,
      chatHistoryDays: 365,
      monthlyApiCalls: 1000,
    },
    features: {
      basicSearch: true,
      aiChat: true,
      citations: true,
      deepResearch: true,
      contractDrafting: true,
      contractAnalysis: true,
      documentUpload: true,
      exportPdf: true,
      exportDocx: true,
      teamManagement: true,
      roleBasedAccess: true,
      sharedWorkspaces: true,
      activityLogs: true,
      ssoSaml: false,
      customIntegrations: false,
      apiAccess: true,
      dedicatedSupport: false,
    },
  },
  {
    tier: "enterprise",
    name: "Enterprise",
    description: "Custom solutions for large organizations",
    monthlyPrice: 0,
    annualPrice: 0,
    isPerSeat: true,
    minSeats: 10,
    trialDays: 0,
    limits: {
      monthlyAiQueries: null,
      storageGb: null,
      maxMembers: null,
      monthlyDeepResearch: null,
      monthlyContractDrafts: null,
      monthlyContractAnalyses: null,
      chatHistoryDays: null,
      monthlyApiCalls: null,
    },
    features: {
      basicSearch: true,
      aiChat: true,
      citations: true,
      deepResearch: true,
      contractDrafting: true,
      contractAnalysis: true,
      documentUpload: true,
      exportPdf: true,
      exportDocx: true,
      teamManagement: true,
      roleBasedAccess: true,
      sharedWorkspaces: true,
      activityLogs: true,
      ssoSaml: true,
      customIntegrations: true,
      apiAccess: true,
      dedicatedSupport: true,
    },
  },
];

export async function GET() {
  return NextResponse.json({
    tiers: PRICING_TIERS,
    currency: "USD",
  });
}
